### ISSUE TITLE
Access Denied? [Docker]

### ISSUE THREAD

**Issue by FakadoDev** [oprogram/LibreNote#3]
Alright so, I've recently been "stalking" this project because it caught my interest but haven't tried it for myself until yesterday. I downloaded the source code and I set up everything perfectly fine (I'm trying the docker step). Now this is where the interesting part starts. 

Setting up Redis was flawless. No issues. But here's the problem; `docker pull ghcr.io/librenotebot/librenote:latest` -> _Output;_ `Error response from daemon: Head "https://ghcr.io/v2/librenotebot/librenote/manifests/latest": denied`

It seems like I cannot pull the content? I'm using the latest nodeJS version and the WebStorm IDE. The Redis docker is fully functional and I am using a windows machine. I have also tried setting it up on my kali linux virtual machine but without success (needed to upgrade node and I was too lazy to do it)

Any suggestions on what I should do? 

**I'm more active in discord so if I do not respond here you can contact me over there!**

Fakado#8525

**Comment by Ulferno** [comment]
Hi there.

We recently changed our organisation name to **oprogram** from **librenotebot** so the image name has changed to `ghcr.io/librenotebot/librenote:latest`. 

I'll update the outdated guide later.

**Comment by FakadoDev** [comment]
Ah alright I should have figured that out. My bad.

**Comment by Ulferno** [comment]
453b545
